config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(article_params)
    @flat.save
    redirect_to flats_path
  end

private

def article_params
  params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_URL)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>List of all flats</h1>
<ul>
<% @flats.each do |flat| %>
<li  class="card">
<%= flat.name %>
<%= flat.address %>
<%= flat.price_per_night %>
<%= flat.number_of_guests %>
</li>
<li>
  <%= link_to 'More Info', flat_path(flat), class: "btn btn-primary"  %>
</li>
<% end %>
</ul>
<img src="https://images.unsplash.com/photo-1513584684374-8bab748fbf90?ixlib=rb-1.2.1&auto=format&fit=crop&w=1492&q=80" alt="">

app/views/flats/new.html.erb
<h1>Add a new flat!</h1>

<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :picture_URL %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/show.html.erb
<ul>
<li><%= @flat.name %></li>
<li><%= @flat.address %></li>
<li><%= @flat.description %></li>
<li><%= @flat.price_per_night %> euros per night</li>
<li><%= @flat.number_of_guests %> guests </li>
</ul>

<img src="<%= @flat.picture_URL %>" alt="flat">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://cdn5.vectorstock.com/i/1000x1000/35/49/bed-icon-circle-vector-15603549.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Add Flat", new_flat_path, class: "btn btn-primary" %>
      </li>
 <!--      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li> -->
    </ul>
  </div>
</div>
    <%= yield %>
  </body>
</html>